ARG VARIANT=latest
FROM node:$VARIANT

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
	&& apt-get install -y git psmisc wget \
	&& apt-get clean

RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
	&& apt-get install -y --no-install-recommends make cmake dotnet-sdk-6.0 \
	&& apt-get clean

RUN dotnet tool install --global dotnet-ef

WORKDIR /app